site_name: CommonRoad Velocity Planner

theme:
  name: material
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: false
            heading_level: 3
            show_module_names: False
  - search

nav:
  - Introduction:
    - "Introduction": index.md

  - Example Usage:
      - "Fast API": fast_api.md
      - "Long Example": long_example.md

  - Core API:
      - "Race Track": racetrack.md
      - "Race Line": raceline.md
      - "Shortest Path Planner": spp.md
      - "Minimum Curvature Planner": mcp.md
      - "Visualization": visualization.md


